### ISSUE TITLE
Mix task to produce an image

### ISSUE THREAD

**Issue by am-kantox** [am-kantox/finitomata#1]
▸ command line: https://plantuml.com/en/command-line
▸ tools: https://plantuml.com/en/running

Mix task should simply call `java -jar plantuml.jar file` for starters, assuming `file` is the FSM description as by code surrounded with `@startuml`/`@enduml` markers.

**Comment by l3nz** [comment]
It would be better to use Mermaid as in https://fireproofsocks.medium.com/enhancing-elixir-documentation-with-mermaid-charts-340fad5c6426 because it would make it trivial to have them embedded in the module documentation.

**Comment by am-kantox** [comment]
Hi @l3nz!

Thanks for your input, this issue description should absolutely be reworded because it has been created _before_ `finitomata` ever met mermaid support.

Anyway, the mix task would be good, although minor addition to what we already have because docs are already generating pictures with `mermaid`.
