### ISSUE TITLE
Recommendations for custom state payload assertions in tests

### ISSUE THREAD

**Issue by kevgathuku** [am-kantox/finitomata#100]
Hello 👋🏾 

I've started using `Finitomata` to model a card game and it works amazing.
Much better than whatever I was doing before.

However, when it comes to testing I'm having some challenges checking the state payload.
So far, using `assert_payload` is great for checking what needs to be in the state after transitions.

However, I'm struggling with checking the state for things like:
- the length of a certain property in the state payload

Example:
```elixir
# Inside state transition to deal some cards to the players
# Verify how many cards have been dealt to each player
# We don't want to check exactly which cards they are, just the no. of cards
assert length(payload.player_1.cards) == 4
assert length(payload.player_2.cards) == 4

# Veryify how many cards remain in the deck
assert length(payload.deck) == 44
```

- the non-existence of certain keys in the state payload

Example:
```elixir
refute match?(%{payload: %{obviously_this_is_invalid: _}}, state)
```

I've gone through the examples and can't see a case of custom assertions on the state, when using the test helpers.
How can these assertions fit in with the `assert_transition` and `assert_payload` test helpers?

```elixir
test "some", ctx do
  assert_transition ctx, {:increase, 1} do
    :counted ->
      assert_payload do
		# Is it possible to check the length of a list here?
        user_data.counter ~> 2
        internals.pid ~> ^parent
      end
  end
end
```

I've gone through the examples and can't see a case of custom assertions on the state, when using the test helpers Is there some example or some recommendation on how to do this?

Or is the only way around it to use the low level approach like here?
https://github.com/am-kantox/finitomata/blob/582245498ffee01f315bdea84445c388d60fb5b5/test/finitomata/ex_unit_test.exs#L10-L41

Thanks for the amazing library 🙏🏾

**Comment by kevgathuku** [comment]
I finally went with something like this:

```elixir
test "start with bogus config", %{finitomata: %{fsm: fsm}} do
  Finitomata.transition fsm.name, {:start, {obviously_this_is_invalid: 67}}
  state = Finitomata.state fsm.name

  refute match?(%{payload: %{rules: %{obviously_this_is_invalid: _}}}, state)
end
```

Will close the issue for now, but happy to hear if there's better ways to handle such scenarios, especially when dealing with a sequence of state transitions

**Comment by am-kantox** [comment]
> Package published to https://hex.pm/packages/finitomata/0.20.2
> (7bdeeac64746dc37ed5b22bc990bbf106825b0bbeb13a6af44b0c3bcc0d9edfe)

Hi @kevgathuku! 

Thanks for reporting this. Effective now any syntax accepted by `Kernel.match?/2` as the first argument is supported on the right side of `~>` meaning you might do

```elixir
assert_payload do
  internals.value ~> list when is_list(list) and length(list) == 4
end
```
