### ISSUE TITLE
warning, only once: unhandled finitomata declaration

### ISSUE THREAD

**Issue by aus70** [am-kantox/finitomata#101]
When I modify the FSM declaration, I get the following warning only once, the first time I compile the code:

```
warning: unhandled finitomata declaration found in MyApp.FiniteStateMachine,
         but we were unable to analyse the correctness of the FSM.
         Add :finitomata compiler to compilers: in your mix.exs!
```

I added :finitomata to the compilers in mix.exs.

Am I missing anything?
Thanks!

**Comment by am-kantox** [comment]
Hi @aus70, sorry for the late response.

> When I modify the FSM declaration, I get the following warning only once, the first time I compile the code:

The `:finitomata` compiler should print this warning every time the file containing the definition gets recompiled (read: has been changed.) It follows the general principle of how any elixir compiler is supposed to behave, it writes a manifest and if nothing has changed, nothing gets recompiled.

Unlike errors, warnings do not prevent the successful compilation, and hence no warning is expected from this file until it is recompiled.

If you consider this behaviour confusing (I kinda do,) I’d love to see the proposal of how you’d like it to behave. Finitomata compiler writes its own manifest file and therefore we might mark the file as not compiled unless there is no warning from this particular compiler, but I dislike it either.

**Comment by am-kantox** [comment]
> I added `:finitomata` to the compilers in `mix.exs`.

After I gave the second read, I figured out I might have misunderstood your question. If the question is why it ever gets printed even though the compiler is there in `mix.exs`, there might be one of the following reasons:

- wrong order of compilers
- it has been compiled previously without the `:finitomata` compiler and hence the manifest is somewhat missing

In any case, fresh `mix do clean, compile` should shut this warning up once and forever.

**Comment by aus70** [comment]
Hi @am-kantox , thank for your answer. The issue was caused by the compiler being in the wrong position: moving it to the beginning of the list does the trick: no more warnings.

For the records, here is the right way to do it:

```
def project do
    [
     ...
      compilers: compilers(Mix.env())
    ]
  end
```

`defp compilers(_), do: [:finitomata | Mix.compilers()]`

Thank you!
