### ISSUE TITLE
Functions specs are not correct

### ISSUE THREAD

**Issue by egidijusz** [am-kantox/finitomata#15]
Functions, accepting "FSM name" as an argument (`transition`, `state`, `allowed?`, etc.), have wrong typespec.
Type `GenServer.name` does not cover String.t() for one (fsm name as string is used in documentation examples).

It should be `any()`, as in function `fqn/0`. Since fsm name is always passed to that function anyway.

**Comment by am-kantox** [comment]
Hi @egidijusz, thanks for the PR. indeed, of course.

**Comment by egidijusz** [comment]
Thank you!

**Comment by am-kantox** [comment]
FWIW, 
> Package published to https://hex.pm/packages/finitomata/0.5.1
> (8584258c1d030f4340e7bc1506dc66d7a8185b696505f80958cc3bb4292ae5d8)
