### ISSUE TITLE
confusion about mermaid syntax

### ISSUE THREAD

**Issue by egidijusz** [am-kantox/finitomata#25]
Hello,

this is not an issue per se, I'm just confused :)
Finitomata (as per README and code) supports two FSM description "syntaxes": [PlantUML](https://plantuml.com/en/state-diagram) and [Mermaid](https://mermaid.live) .
Where Mermaid looks like this:
```
s1 --> |to_s2| s2
s1 --> |to_s3| s3
```

But the actual Mermaid syntax (both on their [docs](https://mermaid-js.github.io/mermaid/#/stateDiagram) and [live editor](https://mermaid.live/edit#pako:eNpt0LEOwiAQBuBXITeadijdGJx0dHIUYy7l1KZSDFxNTNN3l1JqYuJN8PFD7hihcYZAQWBk2rV482jLl9S9iHXanEVZbkWohBLsLqFaPO4Ty8zyl-vMdWaZeH5MCddlrP_gWlCAJW-xNbGzcT7TwHeypEHFpUHfadD9FHPD08TG96Zl50Fd8RGoABzYHd99A4r9QGsoT_dNUbp0WOZP3zB9ANtOT2k)) is not like this.
It's like this (basically a PlantUML syntax):
```
    [*] --> s1 : to_s1
    s1 --> s2 : to_s2
    s1 --> s3 : to_s3
    s2 --> [*] : ok
    s3 --> [*] : ok
```

Also, Finitomata's Mermaid syntax actually does not work on Mermaid's live editor, [example here](https://mermaid.live/edit#pako:eNpljTEKwzAQBL9ybG0VsTsVrvKDtIJwWOfYYElBOgWC7b9HqVKkW4ZhdseUvMCiKKtcV35kDubVu0hULmTMSIeme-kPKn9waHBAhyA58OpbZf8qDrpIEAfbppeZ66YOLp5N5arp9o4TrOYqHerT_35hZ96KnB_p-zDn)

Hence my confusion. **Where does the Mermaid syntax comes from?** Is it older Mermaid version? Am I missing something obvious here? 

P.s. I do vaguely remember that Mermaid (years ago?) had different syntax for State diagrams that looked like `s1 --> |to_s2| s2`. But I'm not sure, might be confusing it with some other tool.

**Comment by am-kantox** [comment]
The confusion comes from Mermaid’s supporting different syntaxes and I’ve chosen _graph_ example (most likely erroneously.)

https://mermaid.live/edit#pako:eNpdjjEOwjAQBL9y2jopSDoXVOEFUFpCp_ggFjiO7HOBkvwdI0RDtzualXbFGJ3A4J54megy2JkoH6htj7RpvOZuo9z9w77CHg2CpMDe1fn6USx0kiAWpkbH6WFh5716ZXGscnJeY4LRVKQBF43n1zz--tcZPNcnAebGzyz7G4dJNBc

Note “graph TD” as a caption. I shall probably re-think naming :)

**Comment by egidijusz** [comment]
Thank you for your answer!

So to summarize:
PlantUML (in Finitomata) syntax is actually a PlantUML's `state-diagram` **and** Mermaid's `stateDiagram-v2` syntax. Those two are kinda identical.
Mermaid (in Finitomata) syntax is Mermaid's `graph` syntax (which his now called `flowchart`, I think).

Is this correct?

**Comment by am-kantox** [comment]
Exactly. I [have updated docs](https://hexdocs.pm/finitomata/readme.html) to make it less confusing; it’s a shame I didn’t make it clear enough from scratch.

The default is Mermaid's `graph` (which is now called `flowchart`.) 

“[Now we have 15 standards](https://xkcd.com/927).”

**Comment by am-kantox** [comment]
I am closing this issue because it seems to be cleaned up. If you have some further questions, please don’t hesitate to reopen it.

**Comment by egidijusz** [comment]
Thank you!

Maybe it would be worth it to rename `Parser.Mermaid` to `Parser.Flowchart` or `Parser.MermaidFlowchart` or something like that?

I could go ahead and do it if you're okay with this.

P.s. since I can't reopen this issue I've created new one (#26) with same question.
