### ISSUE TITLE
mermaid compiler error

### ISSUE THREAD

**Issue by ray-sh** [am-kantox/finitomata#35]
Hi,
I got the following error but can't figure out what's wrong here.
I could parser the mermaind through https://mermaid.live with the @mermaid data.

(TokenMissingError)  description is incomplete, error: initial_state

Stacktrace:
  │ lib/locker.ex:11: (module)

```
defmodule Locker do

  @mermaid """
    s1 --> |click_1| s2
    s1 --> |click_n1| s1
    s2 --> |click_2| s3
    s2 --> |click_n2| s1
    s3 --> |click_3| s4
    s3 --> |click_n3| s1
  """
  use Finitomata, fsm: @mermaid, syntax: Finitomata.Mermaid

  @impl Finitomata
  def on_transition(:s1, :click_1, event_payload, state_payload),
    do: {:ok, :s2, state_payload}
end
```

**Comment by am-kantox** [comment]
For the sake of easy internal consistency, there could be only 1 starting state (this might be fixed soon.)

ATM, use smth like 

``` 

idle --> |init!| s1 
...
```

**Comment by am-kantox** [comment]
Add `:finitomata` to compilers and you will get back meaningful errors.

**Comment by ray-sh** [comment]
I checked the hex doc there is no such option for using schema or config.exs. 
Could you  let me how to add  :finitomata to compilers?
Thanks

**Comment by am-kantox** [comment]
> I checked the hex doc there is no such option for using schema or config.exs. 
> Could you  let me how to add  :finitomata to compilers?

This is not somewhat specific to this library, this is a generic `mix` feature https://hexdocs.pm/mix/Mix.html#compilers/0

**Comment by ray-sh** [comment]
Finally, I got to understand the big picture of mix compiler from you lib.
Thanks!
