### ISSUE TITLE
Duplicated field name of payload

### ISSUE THREAD

**Issue by ray-sh** [am-kantox/finitomata#36]
There are two fields "payload"

20:12:21.894 [warning] [✗⥯] [state: %Finitomata.State{name: {:via, Registry, {Finitomata.Registry, "stile"}}, lifecycle: :unknown, persistency: nil, listener: nil, current: :locked, payload: nil, timer: false, history: [:built, :*], last_error: nil}, event: :off, payload: 9999]

Maybe named the second one to event_payload?

If you think this is issue, I could send a MR for this.

**Comment by am-kantox** [comment]
> There are two fields "payload"
> 
> 20:12:21.894 [warning] [✗⥯] [state: %Finitomata.State{name: {:via, Registry, {Finitomata.Registry, "stile"}}, lifecycle: :unknown, persistency: nil, listener: nil, current: :locked, payload: nil, timer: false, history: [:built, :*], last_error: nil}, event: :off, payload: 9999]

> If you think this is issue, I could send a MR for this.


Yeah, the main issue would be a better implementation of Inspect protocol in general.

MR would be much appreciated.

**Comment by ray-sh** [comment]
Look like this is just a tiny naming issue.
I thought just need rename payload to event_payload https://github.com/am-kantox/finitomata/blob/v0.11.0/lib/finitomata/hook.ex#L128
Same one as https://github.com/am-kantox/finitomata/blob/v0.11.0/lib/finitomata/hook.ex#L112

I am not quite sure what do you mean "implementation of Inspect protocol in general"
