### ISSUE TITLE
Add behaviour for different formats

### ISSUE THREAD

**Issue by am-kantox** [am-kantox/finitomata#4]
- `parse/1`
- `lint/2`

**Comment by ray-sh** [comment]
Do you mean move Finitomata.Mermaid.parse Finitomata.PlantUML.parse to a behavior?

**Comment by am-kantox** [comment]
> Do you mean move Finitomata.Mermaid.parse Finitomata.PlantUML.parse to a behavior?
> 

~~No, no. I am far from computer right now, I do not remember if Inspect protocol is implemented for Finitomata, but what you see would be what is produced by Inspect. I will be back from a trip tomorrow morning and I will fix it and share.~~

**Comment by am-kantox** [comment]
@ray-sh ok, I should stop trying to answer questions from my phone without glasses :)

Yes, this issue is to introduce a behaviour for different parsers and make both `Finitomata.Mermaid` and `Finitomata.PlantUML` implement this behaviour.

**Comment by ray-sh** [comment]
Got it, working on the fix.
Seems It's holiday time in your place. No rush :).

**Comment by am-kantox** [comment]
> Seems It's holiday time in your place. No rush :).

Not at all, I just took a short vacation. I have it implemented already because it was my fault for answering it properly in the first place. Also, #26 has been also involved, so I did it at once.

**Comment by am-kantox** [comment]
@ray-sh sorry for the mess, I already amended the code with all your suggestions.

I strongly appreciate your willingness to help, hopefully, along the path of using it, we’ll get more things to code :)

> Package published to https://hex.pm/packages/finitomata/0.11.1
> (558da8e28e536b5cb3ca937a400df01d3efb2dd91414aecd6a0041da069b0064)
