### ISSUE TITLE
No call/cast ?

### ISSUE THREAD

**Issue by a3kov** [am-kantox/finitomata#52]
After reading the description, it seems this FSM implementation does not allow processing of custom events, other than transitioning...or am I missing something ? What if I want to process some messages differently depending on the state ?

**Comment by am-kantox** [comment]
> this FSM implementation does not allow processing of custom events

That’s what makes it a correct implementation. One cannot interfere with the FSM lifecycle in any way except through transitions.

> What if I want to process some messages differently depending on the state?

[`on_transition/4`](https://hexdocs.pm/finitomata/Finitomata.html#c:on_transition/4) callback is where you can pattern-match on state, event, event payload and return the new state back.

**Comment by a3kov** [comment]
That is a very bold statement. In `get_statem` there's `data` which is separate from `state`, and not every event changes the state. It's up to the developer to decide what is the state in the application.

**Comment by am-kantox** [comment]
> In `get_statem` there's `data` which is separate from `state`

In `Finitomata` there is `payload` which is roughly what `Data` is in `gen_statem`.

> and not every event changes the state

Of course.

> It's up to the developer to decide what is the state in the application.

Not at all. All Erlang in general and [Joe Armstrong’s thesis](https://erlang.org/download/armstrong_thesis_2003.pdf) in particular is about one cannot interfere with the state in any way but sending messages. `Finitomata` restricts the interop with running FSMs to sending events with payloads aka transitions.

**Comment by a3kov** [comment]
And that's my point, this implementation is very limiting. Let's take faucet as an example - its a state machine, but running water does not change the state or care about the faucet implementation. If you tried to implement a faucet using your library it would not accept water at all, or if it did, it would ask the water pipes to be aware of the faucet implementation.
There are many types of state machines that need to process data based on state - and this library is completely missing this use case.

**Comment by am-kantox** [comment]
Running water has nothing to do with a tap implementation, which works _absolutely_ the same whether the water exists or not.

> There are many types of state machines that need to process data based on state - and this library is completely missing this use case.

And it will stay that way forever.

**Comment by a3kov** [comment]
>Running water has nothing to do with a tap implementation, which works absolutely the same whether the water exists or not.

Sure, they are not related at all. If you are building faucets for a museum, and not planning to run them.
Seems like you want to be right at all costs, instead of opening your mind to a new idea.
Ok, you are right. Cheers.

**Comment by am-kantox** [comment]
The last thing I care about is being right.

I simply have absolutely no plans to allow custom messages in this particular library. Period. This is by no means a “new idea,” neither is it somewhat people cannot grasp. It could even perfectly work somewhere else.

Just not next to my code.
