### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by james-the-elixir-guy** [am-kantox/finitomata#68]
Please release new version on hex, thanks :)

**Comment by james-the-elixir-guy** [comment]
I want to use this library in a hex package but I need the persistency stuff to be working.
🥺

**Comment by peaceful-james** [comment]
Good sir, kindly `mix hex.publish` and I will give you 1,000 [bottle caps](https://fallout.fandom.com/wiki/Bottle_cap)

**Comment by am-kantox** [comment]
Hi @peaceful-james, sorry for the silence, I was on vacation far from the computer.
I am not sure what this request is about. The `ecto` persistency was never meant to be included in this library. Persistency works, as a scaffold; you might implement any kind of persistency with it, and `ecto` one is just an example (not even robust enough yet.)
Whether you are after the implementation given in the example, you are to copy-paste it and tune it for your own needs.

**Comment by peaceful-james** [comment]
I want this:
https://github.com/am-kantox/finitomata/pull/60
to be on the hex version.

Just release the latest commit on hex please. THanks!

**Comment by am-kantox** [comment]
> Package published to https://hex.pm/packages/finitomata/0.14.6 
> (a887905952d828b21bde78671cd8b712ecb2e40af663a3ce3ff04b605bcb3bc9)
